### ISSUE TITLE
feat : star for restaurant

### ISSUE THREAD

**Issue by vinhyenvodoi98** [anhtuhsp/Goshare_rails_project#30]
follow
https://ant.design/components/rate/

**Comment by tienthegainz** [comment]
@vinhyenvodoi98 please give clear instruction on this task

**Comment by vinhyenvodoi98** [comment]
@tienthegainz 
![image](https://user-images.githubusercontent.com/33363513/71306324-5d80fd80-2411-11ea-84ec-50ba0c0eefe7.png)
when click on image in newfeed just show how many michelin star restaurants have
